export const challegeTypes =
    [
        "Use a Legend's Ability",
        "Collect crafting materials or use a replicator",
        "Deal damage",
        "Finish a match",
        "Restore health/Revive teammates",
        "Kills, Knockdowns, Assists",
        "Loot",
        "Play",
        "Purchase/Upgrade",
        "Scan beacons",
        "Survive/Outlive",
        "Win"
    ]
export const challengeExamplesArray =
    [
        "Play [X] games as [legends]",
        "Deal [X] damage as [legend]",
        "Deal [X] damage with [type of weapon]",
        "Deal [X] damage in a single match",
        "Get [X] kills",
        "Get [X] kills as [legend]",
        "Get [X] kills with [type of weapon]",
        "Get [X] kills in a single match",
        "Get [X] kills with [type of weapon] in a single match",
        "Get [X] knockdowns as [legend]",
        "Get [X] knockdowns with [type of weapon]",
        "Get [X] headshots as [legend]",
        "Get [X] headshots with [type of weapon]",
        "Outlive [X] opponents",
        "Get a Top 3 finish [X] times",
        "Finish in the top 3 as [legends]",
        "Loot [X] epic items",
        "Loot [X] legendary items",
        "Loot a legendary [piece of Gear] [X] times",
        "Deal [X] damage with Bangalore's Rolling Thunder",
        "Scan [X] enemies as Bloodhound",
        "Scan [X] traps as Bloodhound",
        "Get [X] kills while Beast of the Hunt is active as Bloodhound",
        "Have [X] gas traps activated as Caustic",
        "NOX: [X] damage dealt as Caustic",
        "NOX: Kill [X] enemies as Caustic while they are gassed",
        "Neurolink: Scan [X] enemies as Crypto",
        "Block [X] damage with Gibraltar's Gun Shield",
        "Get [X] kills with Gibraltar's Bombardment",
        "Heal [X] health with Lifeline's healing drone",
        "[X] items looted by squadmates from Lifeline's care package",
        "Create [X] decoys as Mirage",
        "[X] successful bamboozles as Mirage",
        "Regenerate [X] health as Octane",
        "Launch [X] squadmates off jump pads as Octane",
        "Scan [X] survey beacons as Pathfinder",
        "Pathfinder's zipline used [X] times by squadmates",
        "Rift: Phase [X] squadmates as Wraith",
        "Travel [X] meters in a vehicle"
    ]
