"""made  clanUsers

Revision ID: 90adea3dfcc1
Revises: 6c2527ba0033
Create Date: 2022-02-16 13:45:02.225463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90adea3dfcc1'
down_revision = '6c2527ba0033'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clanusers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clan_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clan_id'], ['clans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clanusers')
    # ### end Alembic commands ###
