"""added season column, default val = 12

Revision ID: b4bfd211c357
Revises: 2869f5afff07
Create Date: 2022-03-09 20:39:25.596147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4bfd211c357'
down_revision = '2869f5afff07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userchallenges', sa.Column('season', sa.Integer(), nullable=False, server_default=sa.text("12")))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userchallenges', 'season')
    # ### end Alembic commands ###
