"""fixed issue with weapon

Revision ID: 6c2527ba0033
Revises: 7c47d0cc76ff
Create Date: 2022-02-16 13:31:04.402015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c2527ba0033'
down_revision = '7c47d0cc76ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('userchallengesdimensiontable_weapon_id_fkey', 'userchallengesdimensiontable', type_='foreignkey')
    op.create_foreign_key(None, 'userchallengesdimensiontable', 'weapons', ['weapon_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userchallengesdimensiontable', type_='foreignkey')
    op.create_foreign_key('userchallengesdimensiontable_weapon_id_fkey', 'userchallengesdimensiontable', 'userchallenges', ['weapon_id'], ['id'])
    # ### end Alembic commands ###
