"""empty message

Revision ID: 2869f5afff07
Revises: 6b99abe62799
Create Date: 2022-02-17 16:26:49.576920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2869f5afff07'
down_revision = '6b99abe62799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clans', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clans', 'description')
    # ### end Alembic commands ###
